# This is a basic workflow to help you get started with Actions

name: Benchmark
on:
  workflow_dispatch:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: install
        run: npm ci
      - name: Benchmark
        run: npm run benchmark